### ISSUE TITLE
@thomasjbradley Z-index problems

### ISSUE THREAD

**Issue by sydbross** [sydbross/portfolio#1]
@thomasjbradley i can't figure out how to get my header to do what i want, which is have the right shape be floated strictly to the right, left shape to the left, then the middle shape, obviously stuck to the middle. then, when the screen size gets smaller, the right and left come in behind the middle but the middle stays stuck there. easy solution to this i am not seeing?

**Comment by thomasjbradley** [comment]
I think the best solution would be to use multiple background images to accomplish it. Here are some videos and tutorials and such to help you out:

- https://learn-the-web.algonquindesign.ca/topics/using-images/#multiple-background-images
- https://www.youtube.com/watch?v=dt6Af0V-Xxw&index=5&list=PLWjCJDeWfDdewUQe57s3Tuktg_8eT0yA7
- https://learn-the-web.algonquindesign.ca/topics/images-cheat-sheet/#css-background-images
